version: '3.4'


services:

  ecommerce:
    image: gvfs/spring-boot-ecommerce:1.0.1
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/full-stack-ecommerce?useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=*****
      
    expose:
      - "8080"
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
      
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.29
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=****
      - MYSQL_DATABASE=full-stack-ecommerce
      
networks:
  springmysql-net:
    driver: bridge
      